---
zabbix:
  user: user
  pass: pass
  server: https://zabbix.example.com
  https-verify: true

cachet:
  token: api token
  server: https://cachet.example.com
  https-verify: true

settings:
  # IT Service which will be a root for Cachet Components
  # Leave it empty if you want to use /
  root_service: ''

  # How often check Zabbix for new incidents
  update_inc_interval: 120  # in seconds
  # How often check Zabbix for new IT Services
  update_comp_interval: 3600  # in seconds


  # Log level https://docs.python.org/3.4/library/logging.html#levels
  log_level: INFO
  # Additional logging level for requests module
  log_level_requests: WARNING

  # Time Zone Info - Used in templates to show time of zabbix events
  # Leave None if you want to use the system timezone zabbix-cachet is running on.
  # Formats accepted: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones - Use Column TZ database name
  time_zone: null

# Templates for incident displaying
# Fill free to use Markdown
templates:
  # Template for acknowledgements (acknowledgement)
  # Supported fields:
  #   message: acknowledgement msg
  #   ack_time: acknowledgement time
  #   author: First name + Surname of Zabbix user
  acknowledgement: |
    {message}
    ###### {ack_time} by {author}
    ______

  # Template for new incinents (investigating)
  # Supported fields:
  #   group: Cachet Group
  #   component: Cachet Component
  #   time: Zabbix event time
  #   trigger_name: Zabbix trigger name
  #   trigger_description: Zabbix trigger description (comment)
  investigating: |
    {group} | {component} check **failed** - {time}

    ```{trigger_name}```

  # Template for resolved incinents (resolving)
  # Supported fields:
  #   time: Incindent resolved time in Cachet
  resolving: |
    __Resolved__ - {time}
    ______